# Site settings
title: Fran√ßois Gouteroux
description: IT Challenger, Automation Geek
url: "https://fgouteroux.github.io"
baseurl: ""

# Social
github_username: fgouteroux
twitter_username: fgouteroux

# Header
header_description: IT Challenger, Automation Geek

# Social Icons
social-icons:
  - title: GitHub
    url: https://github.com/fgouteroux
    class: github
  - title: X (Twitter)
    url: https://x.com/fgouteroux
    class: twitter
  - title: Email
    url: mailto:francois.gouteroux@gmail.com
    class: envelope

# Theme
# theme: jekyll-theme-midnight
plugins:
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .travis.yml
  - vendor/
  - index.html.old
  - index.md.backup
  - resume.md
